// Auto-generated by DSL2Translator from LeaveApproval.dsl2
// Process: Leave Request Approval
// This file is the result of running translator.js on example.dsl2
// It is included here for documentation purposes.

(function() {
  'use strict';

  /* ---- Process Definition ---- */
  const PROCESS_DEF = {
    "name": "LeaveApproval",
    "title": "Leave Request Approval",
    "roles": ["Applicant", "Manager", "Director", "Supervisor"],
    "documents": {
      "LeaveRequest": {
        "states": ["template", "submitted", "manager_approved", "director_approved", "rejected"]
      }
    },
    "startEvent": "ProcessStart",
    "endEvent": "ProcessEnd",
    "steps": [
      {
        "type": "function",
        "name": "FillAndSubmit",
        "role": "Applicant",
        "system": "WebForm",
        "input_doc": ["LeaveRequest.template"],
        "output_doc": ["LeaveRequest.submitted"],
        "on_complete": [
          { "event": "RequestSubmitted", "condition": null, "output_doc": null, "next": "ApproveByManager" }
        ]
      },
      {
        "type": "function",
        "name": "ApproveByManager",
        "role": "Manager",
        "system": "WebForm",
        "input_doc": ["LeaveRequest.submitted"],
        "output_doc": ["LeaveRequest.manager_approved"],
        "on_complete": [
          { "event": "ManagerApproved",  "condition": "decision == 'approved'", "output_doc": "LeaveRequest.manager_approved", "next": "ApproveByDirector" },
          { "event": "ManagerRejected",  "condition": "decision == 'rejected'", "output_doc": "LeaveRequest.rejected",         "next": "NotifyRejection"   }
        ]
      },
      {
        "type": "function",
        "name": "ApproveByDirector",
        "role": "Director",
        "system": "WebForm",
        "input_doc": ["LeaveRequest.manager_approved"],
        "output_doc": ["LeaveRequest.director_approved"],
        "on_complete": [
          { "event": "DirectorApproved", "condition": "decision == 'approved'", "output_doc": "LeaveRequest.director_approved", "next": "NotifyApproval"   },
          { "event": "DirectorRejected", "condition": "decision == 'rejected'", "output_doc": "LeaveRequest.rejected",          "next": "NotifyRejection" }
        ]
      },
      {
        "type": "function",
        "name": "NotifyApproval",
        "role": "System",
        "system": "NotificationService",
        "input_doc": ["LeaveRequest.director_approved"],
        "output_doc": [],
        "on_complete": [
          { "event": "ApprovalNotified", "condition": null, "output_doc": null, "next": "end" }
        ]
      },
      {
        "type": "function",
        "name": "NotifyRejection",
        "role": "System",
        "system": "NotificationService",
        "input_doc": ["LeaveRequest.rejected"],
        "output_doc": [],
        "on_complete": [
          { "event": "RejectionNotified", "condition": null, "output_doc": null, "next": "end" }
        ]
      }
    ]
  };

  /* ---- Runtime State ---- */
  let state = null;

  function createInstance() {
    state = {
      tick: 0,
      currentFunction: PROCESS_DEF.steps.length > 0 ? PROCESS_DEF.steps[0].name : null,
      workflowToken: PROCESS_DEF.startEvent,
      docTokens: {
        "LeaveRequest": "template"
      },
      history: [],
      finished: false
    };
    logTick('(init)', null, PROCESS_DEF.startEvent, null);
    return state;
  }

  function logTick(funcName, role, eventFired, docTransitions) {
    state.history.push({
      tick: state.tick,
      function: funcName,
      role: role,
      workflowTokenBefore: state.workflowToken,
      workflowTokenAfter: eventFired,
      docTransitions: docTransitions || {},
      eventFired: eventFired
    });
    state.tick++;
  }

  function execute(role, decision) {
    if (!state || state.finished) {
      return { ok: false, error: 'Process not started or already finished.' };
    }

    const funcDef = PROCESS_DEF.steps.find(s => s.name === state.currentFunction);
    if (!funcDef) {
      return { ok: false, error: 'No active function: ' + state.currentFunction };
    }

    const allowedRole = funcDef.role;
    if (allowedRole !== 'System' && role !== allowedRole && role !== 'Supervisor') {
      return { ok: false, error: 'Role "' + role + '" cannot execute "' + funcDef.name + '" (requires "' + allowedRole + '").' };
    }

    let firedEvent = null;
    for (const oc of funcDef.on_complete) {
      if (!oc.condition) { firedEvent = oc; break; }
      try {
        const result = (new Function('decision', 'return (' + oc.condition + ');'))(decision);
        if (result) { firedEvent = oc; break; }
      } catch(e) { /* skip */ }
    }

    if (!firedEvent) {
      return { ok: false, error: 'No matching event for decision: ' + decision };
    }

    const docTransitions = {};
    if (firedEvent.output_doc) {
      const [docType, docState] = firedEvent.output_doc.split('.');
      if (docType && docState) {
        const prev = state.docTokens[docType];
        state.docTokens[docType] = docState;
        docTransitions[docType] = { from: prev, to: docState };
      }
    } else {
      for (const od of funcDef.output_doc) {
        const [docType, docState] = od.split('.');
        if (docType && docState && !docTransitions[docType]) {
          const prev = state.docTokens[docType];
          state.docTokens[docType] = docState;
          docTransitions[docType] = { from: prev, to: docState };
        }
      }
    }

    state.workflowToken = firedEvent.event;
    logTick(funcDef.name, role, firedEvent.event, docTransitions);

    if (firedEvent.next === 'end') {
      state.currentFunction = null;
      state.finished = true;
      state.workflowToken = PROCESS_DEF.endEvent;
    } else {
      state.currentFunction = firedEvent.next;
      state.workflowToken = firedEvent.next;
    }

    return {
      ok: true,
      event: firedEvent.event,
      nextFunction: state.currentFunction,
      docTokens: { ...state.docTokens },
      finished: state.finished
    };
  }

  function getState()      { return state ? { ...state } : null; }
  function getHistory()    { return state ? [...state.history] : []; }
  function getDefinition() { return PROCESS_DEF; }

  const engine = { createInstance, execute, getState, getHistory, getDefinition };

  if (typeof module !== 'undefined' && module.exports) {
    module.exports = engine;
  } else {
    window['LeaveApprovalEngine'] = engine;
  }
})();
